services:
  - type: web
    name: invoice-generator-by-shivang
    runtime: node
    rootDir: invoice-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
